### ISSUE TITLE
Cannot read property "token" of undefined

### ISSUE THREAD

**Issue by jascination** [lirantal/typeform-client#25]
Using the sample code in the readme to fetch a form, I'm getting:

```
(node:23596) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'token' of undefined
    at Form._fetchResponses (~/node_modules/@lirantal/typeform-client/src/Form/Form.js:95:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Form.fetchFormResponses ~/node_modules/@lirantal/typeform-client/src/Form/Form.js:118:51)
    at async ~/test.js:16:14
```

The error comes from this line in the node module:

```
      if (apiResult.page_count === 1) {
        break
      } else {
        const len = apiResult.items.length
        const lastItem = apiResult.items[len - 1]
        tokenValue = lastItem.token
      }
```

Might need a more defensive fix?

For reference, my form has 6 questions and no responses.

**Comment by lirantal** [comment]
Hey @jascination, thanks for raising an issue.
Indeed looks like there's simply no more data to fetch and hence no token exists.

Would you want to submit a PR that fixes the issue? I'm happy to merge it.
